### ISSUE TITLE
Problem to install the requirements on Windows

### ISSUE THREAD

**Issue by saleh-mehdikhani** [omid3098/Parspeak#1]
Hi,
I am trying to install the requirements on a Windows machine and for one of the requirements, I can't proceed. According to the error message, it's only intended for the macOS:

```
Collecting pyobjc-core==10.3.2 (from -r requirements.txt (line 9))
  Using cached pyobjc_core-10.3.2.tar.gz (935 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      <string>:17: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
      running egg_info
      error: PyObjC requires macOS to build
```

![image](https://github.com/user-attachments/assets/2fbc7f23-f590-464e-9170-87a57110b227)

Is this package compulsory?

**Comment by omid3098** [comment]
The fix is there but the default key combination (Shift+Ctrl+s) does not work on my windows machine as it detects right Ctrl and left Ctrl separately. at least on my keyboard!
For testing purpose simpler hotkey like Shift+q works fine in my test.
